//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.PortfolioAccessSampleDataSource
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class Report { }
#else

	public class Report : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public Report()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/SeattleSlew_UserPermissions.Screens;component/SampleData/PortfolioAccessSampleDataSource/PortfolioAccessSampleDataSource.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private RecordCollection _Data = new RecordCollection();

		public RecordCollection Data
		{
			get
			{
				return this._Data;
			}
		}
	}

	public class Record : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _PortfolioBaseCode = string.Empty;

		public string PortfolioBaseCode
		{
			get
			{
				return this._PortfolioBaseCode;
			}

			set
			{
				if (this._PortfolioBaseCode != value)
				{
					this._PortfolioBaseCode = value;
					this.OnPropertyChanged("PortfolioBaseCode");
				}
			}
		}

		private string _ReportHeading1 = string.Empty;

		public string ReportHeading1
		{
			get
			{
				return this._ReportHeading1;
			}

			set
			{
				if (this._ReportHeading1 != value)
				{
					this._ReportHeading1 = value;
					this.OnPropertyChanged("ReportHeading1");
				}
			}
		}

		private string _ReportHeading2 = string.Empty;

		public string ReportHeading2
		{
			get
			{
				return this._ReportHeading2;
			}

			set
			{
				if (this._ReportHeading2 != value)
				{
					this._ReportHeading2 = value;
					this.OnPropertyChanged("ReportHeading2");
				}
			}
		}

		private string _ReportHeading3 = string.Empty;

		public string ReportHeading3
		{
			get
			{
				return this._ReportHeading3;
			}

			set
			{
				if (this._ReportHeading3 != value)
				{
					this._ReportHeading3 = value;
					this.OnPropertyChanged("ReportHeading3");
				}
			}
		}

		private string _StartDate = string.Empty;

		public string StartDate
		{
			get
			{
				return this._StartDate;
			}

			set
			{
				if (this._StartDate != value)
				{
					this._StartDate = value;
					this.OnPropertyChanged("StartDate");
				}
			}
		}

		private string _OwnedBy = string.Empty;

		public string OwnedBy
		{
			get
			{
				return this._OwnedBy;
			}

			set
			{
				if (this._OwnedBy != value)
				{
					this._OwnedBy = value;
					this.OnPropertyChanged("OwnedBy");
				}
			}
		}
	}

	public class RecordCollection : System.Collections.ObjectModel.ObservableCollection<Record>
	{ 
	}
#endif
}
